name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # runs every day at midnight
  workflow_dispatch:       # allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Sdulaan
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg@dark

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

---

**Step 2:** Enable Actions permissions
> Repo → **Settings** → **Actions** → **General** → set to **"Read and write permissions"** → Save

---

**Step 3:** Run it manually
> Repo → **Actions** → **Generate Snake Animation** → **Run workflow**

---

**Step 4:** After it runs, check that this branch and file exists:
```
Sdulaan/Sdulaan → branch: output → github-contribution-grid-snake-dark.svg
